<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[create user]]>
    </line>
    <line>
      <![CDATA[create contact]]>
    </line>
  </reporter-output>
  <suite started-at="2022-06-08T09:47:33 IST" name="Default suite" finished-at="2022-06-08T09:47:59 IST" duration-ms="25637">
    <groups>
    </groups>
    <test started-at="2022-06-08T09:47:33 IST" name="Default test" finished-at="2022-06-08T09:47:59 IST" duration-ms="25637">
      <class name="Assertion.SoftAndHardAssert">
        <test-method is-config="true" signature="setProperty()[pri:0, instance:Assertion.SoftAndHardAssert@15aab8c6]" started-at="2022-06-08T09:47:34 IST" name="setProperty" finished-at="2022-06-08T09:47:34 IST" duration-ms="7" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setProperty -->
        <test-method is-config="true" signature="LaunchBrowser()[pri:0, instance:Assertion.SoftAndHardAssert@15aab8c6]" started-at="2022-06-08T09:47:34 IST" name="LaunchBrowser" finished-at="2022-06-08T09:47:47 IST" duration-ms="13051" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchBrowser -->
        <test-method signature="testCase()[pri:0, instance:Assertion.SoftAndHardAssert@15aab8c6]" started-at="2022-06-08T09:47:47 IST" name="testCase" finished-at="2022-06-08T09:47:59 IST" duration-ms="12544" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [OrangeHRMHomePage] but found [OrangeHRM]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [OrangeHRMHomePage] but found [OrangeHRM]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Assertion.SoftAndHardAssert.testCase(SoftAndHardAssert.java:58)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[create user]]>
            </line>
            <line>
              <![CDATA[create contact]]>
            </line>
          </reporter-output>
        </test-method> <!-- testCase -->
      </class> <!-- Assertion.SoftAndHardAssert -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
